create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  country text,
  language text,
  birth_date date,
  is_banned boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references auth.users(id),
  reported_id uuid references auth.users(id),
  reason text not null,
  created_at timestamptz not null default now()
);

create table if not exists blocks (
  blocker_id uuid references auth.users(id) on delete cascade,
  blocked_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id)
);

alter table profiles enable row level security;
alter table reports enable row level security;
alter table blocks enable row level security;
